version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: supabase/postgres:15.1.0.147
    container_name: supabase-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme123}
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Supabase Studio (Interface d'administration)
  studio:
    image: supabase/studio:20231123-64a766a
    container_name: supabase-studio
    environment:
      SUPABASE_URL: http://kong:8000
      STUDIO_PG_META_URL: http://meta:8080
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
    ports:
      - "3001:3000"
    depends_on:
      - kong
      - meta
    restart: unless-stopped

  # Kong API Gateway
  kong:
    image: kong:2.8.1
    container_name: supabase-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
    ports:
      - "8000:8000"
      - "8443:8443"
    restart: unless-stopped
    volumes:
      - ./kong.yml:/home/kong/kong.yml:ro

  # Meta Service (pour Studio)
  meta:
    image: supabase/postgres-meta:v0.68.0
    container_name: supabase-meta
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme123}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data:
    driver: local

networks:
  default:
    name: supabase-network
